version: '3.8'  # Upgrade version to 3.8
services:
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./data:/data
      - ./uploads:/uploads
    environment:
      - IMAGE_HEIGHT=512
      - RETRIEVE_K=2
      - BATCH_SIZE=2
      - SCALE_IMAGE=true
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
